hwmon: add a missing namespace import in zhaoxin-cputemp
Previously, kernel builds fails with:

ERROR: modpost: module zhaoxin-cputemp uses symbol
hwmon_device_register_for_thermal from namespace HWMON_THERMAL, but does not
import it.

Include the missing HWMON_THERMAL namespace to fix the build.

Signed-off-by: Mingcong Bai <baimingcong@uniontech.com>