media: platform: phytium_jpeg_core: Convert to platform remove callback returning void
0edb555: platform: Make platform_driver::remove() return void
cause build error, so convert .remove from int to void

Log:
drivers/media/platform/phytium/phytium_jpeg_core.c:1368:20: error: initialization of ‘void (*)(struct platform_device *)’ from incompatible pointer type ‘int (*)(struct platform_device *)’ [-Werror=incompatible-pointer-types]
 1368 |         .remove =  phytium_jpeg_remove,
      |                    ^~~~~~~~~~~~~~~~~~~
drivers/media/platform/phytium/phytium_jpeg_core.c:1368:20: note: (near initialization for ‘phytium_jpeg_driver.<anonymous>.remove’)