net/hinic3:Add Huawei Intelligent Network Card Driver:hinic3
The NIC driver supports the following features:
 *1. Supports IPv4/IPv6 TCP/UDP checksum, TSO, LRO offload and RSS
functions.
  2. Supports interrupt aggregation parameter configuration and
interrupt adaptation.
  3. Supports 802.1Q VLAN (Virtual Local Area Network) offloading
and filtering.
  4. Supports NIC SR-IOV (Single Root I/O Virtualization).
  5. Support PF promiscuous mode
  6. Supports VF QinQ mode.
  7. Supports VF link state configuration and QoS configuration.
  8. Support VF MAC address management.
  9. Support VF spoofchk check.
  10. Support port lighting.
  11. Support Ethernet mouth self-negotiation, support pause frame.

[ WangYuli: Support COMPILE_TEST and fix follow compile error: ]
  drivers/net/ethernet/huawei/hinic3/adapter/sw_cmdq/sw_cmdq_ops.c:78:34: error: expression does not compute the number of elements in this array; element type is 'u16' (aka 'unsigned short'), not 'u32' (aka 'unsigned int') [-Werror,-Wsizeof-array-div]
     78 |         size = sizeof(indir_tbl->entry) / sizeof(u32);
        |                       ~~~~~~~~~~~~~~~~  ^

Link: https://gitee.com/OpenCloudOS/OpenCloudOS-Kernel/pulls/377
signed-off-by:Fuguiming<fuguiming@huawei.com>
Co-developed-by: WangYuli <wangyuli@uniontech.com>
Signed-off-by: WangYuli <wangyuli@uniontech.com>
(cherry picked from commit c8660113dabd02d96db2734263d9b12a4968cb46)
(cherry picked from commit 1fcfa6955a6bb85b74d4b8b87ed6d471a6597ff7)