Input: phytium-keypad: Convert to platform remove callback returning void
0edb555: platform: Make platform_driver::remove() return void
cause build error, so convert .remove from int to void

Log:
drivers/input/keyboard/phytium-keypad.c:562:23: error: initialization of ‘void (*)(struct platform_device *)’ from incompatible pointer type ‘int (*)(struct platform_device *)’ [-Werror=incompatible-pointer-types]
  562 |         .remove     = phytium_keypad_remove,
      |                       ^~~~~~~~~~~~~~~~~~~~~
drivers/input/keyboard/phytium-keypad.c:562:23: note: (near initialization for ‘phytium_keypad_driver.<anonymous>.remove’)