i2c: phytium: Convert to platform remove callback returning void
0edb555: platform: Make platform_driver::remove() return void
cause build error, so convert .remove from int to void

Log:
drivers/i2c/busses/i2c-phytium-platform.c:351:19: error: initialization of ‘void (*)(struct platform_device *)’ from incompatible pointer type ‘int (*)(struct platform_device *)’ [-Werror=incompatible-pointer-types]
  351 |         .remove = phytium_i2c_plat_remove,
      |                   ^~~~~~~~~~~~~~~~~~~~~~~
drivers/i2c/busses/i2c-phytium-platform.c:351:19: note: (near initialization for ‘phytium_i2c_driver.<anonymous>.remove’)