npu:phytium: fix build error in phytium_npu_pci_probe
Log:
2025-05-16T15:13:43.6129337Z drivers/staging/phytium-npu/phytium_npu_pci.c:82:16: error: variable 'reg_addr' is used uninitialized whenever 'for' loop exits because its condition is false [-Werror,-Wsometimes-uninitialized]
2025-05-16T15:13:43.6131548Z    82 |         for (bar = 0; bar < NUM_PCI_BARS; bar++) {
2025-05-16T15:13:43.6132195Z       |                       ^~~~~~~~~~~~~~~~~~
2025-05-16T15:13:43.6133127Z drivers/staging/phytium-npu/phytium_npu_pci.c:98:7: note: uninitialized use occurs here
2025-05-16T15:13:43.6134010Z    98 |         if (!reg_addr)
2025-05-16T15:13:43.6134457Z       |              ^~~~~~~~
2025-05-16T15:13:43.6135385Z drivers/staging/phytium-npu/phytium_npu_pci.c:82:16: note: remove the condition if it is always true
2025-05-16T15:13:43.6136692Z    82 |         for (bar = 0; bar < NUM_PCI_BARS; bar++) {
2025-05-16T15:13:43.6137381Z       |                       ^~~~~~~~~~~~~~~~~~
2025-05-16T15:13:43.6138490Z drivers/staging/phytium-npu/phytium_npu_pci.c:52:24: note: initialize the variable 'reg_addr' to silence this warning
2025-05-16T15:13:43.6139510Z    52 |         void __iomem *reg_addr;
2025-05-16T15:13:43.6140038Z       |                               ^
2025-05-16T15:13:43.6140541Z       |                                = NULL
2025-05-16T15:13:43.6141173Z 1 error generated.
Signed-off-by: Wentao Guan <guanwentao@uniontech.com>
(cherry picked from commit 19c397e69bf13af987936f981507e6e6a22f81fa)
(cherry picked from commit 0035129952ce1f4f8d6e04fd811e7cbfe77d3a42)