iio: adc: phytium: Convert to platform remove callback returning void
0edb555: platform: Make platform_driver::remove() return void
cause build error, so convert .remove from int to void

Log:
drivers/iio/adc/phytium-adc.c:684:27: error: initialization of ‘void (*)(struct platform_device *)’ from incompatible pointer type ‘int (*)(struct platform_device *)’ [-Werror=incompatible-pointer-types]
  684 |         .remove         = phytium_adc_remove,
      |                           ^~~~~~~~~~~~~~~~~~
drivers/iio/adc/phytium-adc.c:684:27: note: (near initialization for ‘phytium_adc_driver.<anonymous>.remove’)