firmware: arm_scmi: mailbox: fix unused var error
Log:
drivers/firmware/arm_scmi/transports/mailbox.c: In function ‘mailbox_chan_setup’:
drivers/firmware/arm_scmi/transports/mailbox.c:189:25: error: unused variable ‘res’ [-Werror=unused-variable]
  189 |         struct resource res;
      |                         ^~~
drivers/firmware/arm_scmi/transports/mailbox.c:188:25: error: unused variable ‘size’ [-Werror=unused-variable]
  188 |         resource_size_t size;
      |                         ^~~~