lpc: phytium-lpc-snoop: Convert to platform remove callback returning void
0edb555: platform: Make platform_driver::remove() return void
cause build error, so convert .remove from int to void

Log:
drivers/misc/phytium-lpc-snoop.c:317:19: error: initialization of ‘void (*)(struct platform_device *)’ from incompatible pointer type ‘int (*)(struct platform_device *)’ [-Werror=incompatible-pointer-types]
  317 |         .remove = phytium_lpc_snoop_remove,
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~
drivers/misc/phytium-lpc-snoop.c:317:19: note: (near initialization for ‘phytium_lpc_snoop_driver.<anonymous>.remove’)