arch: arm64: disable ARM_GIC_PHYTIUM_2500 due to build failure
The following error occurs despite previous code fixes:

ld: drivers/irqchip/irq-gic-phytium-2500.o: in function
`gic_enable_nmi_support':
./drivers/irqchip/irq-gic-phytium-2500.c:1870:(.init.text+0xf1c):
undefined reference to `gic_nonsecure_priorities'
ld: drivers/irqchip/irq-gic-phytium-2500.o: relocation
R_AARCH64_ADR_PREL_PG_HI21 against symbol `gic_nonsecure_priorities' which
may bind externally can not be used when making a shared object; recompile
with -fPIC
./drivers/irqchip/irq-gic-phytium-2500.c:1870:(.init.text+0xf1c):
dangerous relocation: unsupported relocation
ld: drivers/irqchip/irq-gic-phytium-2500.c:1870:(.init.text+0xf20):
undefined reference to `gic_nonsecure_priorities'
ld: drivers/irqchip/irq-gic-phytium-2500.o:(__jump_table+0x68): undefined
reference to `gic_nonsecure_priorities'
ld: drivers/irqchip/irq-gic-phytium-2500.o:(__jump_table+0xa8): undefined
reference to `gic_nonsecure_priorities'

Disable this driver for now as we would like to ship 6.12 for AArch64 and
this piece of support code is probably seldom used by community users.

Signed-off-by: Mingcong Bai <jeffbai@aosc.io>