spi-v2.0: Phytium: fix uninitialized ret in spi_phytium_write
drivers/spi/spi-phytium-common.c:333:7: error: variable 'ret' is uninitialized when used here [-Werror,-Wuninitialized]
   333 |                 if (ret) {
       |                     ^~~
   CC [M]  drivers/input/serio/pcips2.o
 drivers/spi/spi-phytium-common.c:325:9: note: initialize the variable 'ret' to silence this warning
   325 |         int ret;
       |                ^
       |                 = 0
1 error generated.

Signed-off-by: Wentao Guan <guanwentao@uniontech.com>
(cherry picked from commit b20e4b792a7acefa85599467421c7a26835ba5f9)
(cherry picked from commit f943977498ed4fc9ca6b1199f13a7a74be8fc806)