edac: phytium_edac: Convert to platform remove callback returning void
0edb555: platform: Make platform_driver::remove() return void
cause build error, so convert .remove from int to void

Log:
drivers/edac/phytium_edac.c:470:19: error: initialization of ‘void (*)(struct platform_device *)’ from incompatible pointer type ‘int (*)(struct platform_device *)’ [-Werror=incompatible-pointer-types]
  470 |         .remove = phytium_edac_remove,
      |                   ^~~~~~~~~~~~~~~~~~~
drivers/edac/phytium_edac.c:470:19: note: (near initialization for ‘phytium_edac_driver.<anonymous>.remove’)