net: ethernet: phytmac: Convert to platform remove callback returning void
0edb555: platform: Make platform_driver::remove() return void
cause build error, so convert .remove from int to void

drivers/net/ethernet/phytium/phytmac_platform.c:243:19: error: initialization of ‘void (*)(struct platform_device *)’ from incompatible pointer type ‘int (*)(struct platform_device *)’ [-Werror=incompatible-pointer-types]
  243 |         .remove = phytmac_plat_remove,
      |                   ^~~~~~~~~~~~~~~~~~~
drivers/net/ethernet/phytium/phytmac_platform.c:243:19: note: (near initialization for ‘phytmac_driver.<anonymous>.remove’)