usb: phytium_v2: fix uninitialized phytium_usb in phytium_pci_probe
Log:
drivers/usb/phytium_usb_v2/pci.c:33:6: error: variable 'phytium_usb' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
    33 |         if (pci_is_enabled(pdev)) {
       |             ^~~~~~~~~~~~~~~~~~~~
drivers/usb/phytium_usb_v2/pci.c:45:2: note: uninitialized use occurs here
   45 |         phytium_usb->otg_res.start = pci_resource_start(pdev, 0);
      |         ^~~~~~~~~~~
drivers/usb/phytium_usb_v2/pci.c:33:2: note: remove the 'if' if its condition is always true
   33 |         if (pci_is_enabled(pdev)) {
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~
drivers/usb/phytium_usb_v2/pci.c:24:33: note: initialize the variable 'phytium_usb' to silence this warning
   24 |         struct phytium_usb *phytium_usb;
      |                                        ^
      |                                         = NULL
1 error generated.
similar to the following logic:
	pci_set_master(pdev);
	if (pci_is_enabled(func)) {
		cdnsp = pci_get_drvdata(func);
	} else {
		cdnsp = kzalloc(sizeof(*cdnsp), GFP_KERNEL);
		if (!cdnsp) {
			ret = -ENOMEM;
			goto disable_pci;
		}
	}

Signed-off-by: Wentao Guan <guanwentao@uniontech.com>
(cherry picked from commit f3db86f0a2dc6e3a7797d52dc3073e60725d7598)
(cherry picked from commit d7136336842631bc95b36a24fd344b07ef19749e)