char: ipmi: kcs_bmc_phytium: Convert to platform remove callback returning void
0edb555: platform: Make platform_driver::remove() return void
cause build error, so convert .remove from int to void

Log:
drivers/char/ipmi/kcs_bmc_phytium.c:431:19: error: initialization of ‘void (*)(struct platform_device *)’ from incompatible pointer type ‘int (*)(struct platform_device *)’ [-Werror=incompatible-pointer-types]
  431 |         .remove = phytium_kcs_remove,
      |                   ^~~~~~~~~~~~~~~~~~
drivers/char/ipmi/kcs_bmc_phytium.c:431:19: note: (near initialization for ‘phytium_kcs_bmc_driver.<anonymous>.remove’)