perf: phytium_ddr_pmu: Convert to platform remove callback returning void
0edb555: platform: Make platform_driver::remove() return void
cause build error, so convert .remove from int to void

Log:
drivers/perf/phytium/phytium_ddr_pmu.c:666:19: error: initialization of ‘void (*)(struct platform_device *)’ from incompatible pointer type ‘int (*)(struct platform_device *)’ [-Werror=incompatible-pointer-types]
  666 |         .remove = phytium_ddr_pmu_remove,
      |                   ^~~~~~~~~~~~~~~~~~~~~~
drivers/perf/phytium/phytium_ddr_pmu.c:666:19: note: (near initialization for ‘phytium_ddr_pmu_driver.<anonymous>.remove’)