sw64: fix some compile issues for cpuautoplug.c
Fix compiler errors:

In file included from arch/sw_64/kernel/cpuautoplug.c:19:
arch/sw_64/kernel/../../../kernel/sched/sched.h: In function 'update_current_exec_runtime':
arch/sw_64/kernel/../../../kernel/sched/sched.h:3287:9: error: implicit declaration of function 'account_group_exec_runtime' [-Werror=implicit-function-declaration]
 3287 |         account_group_exec_runtime(curr, delta_exec);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~

arch/sw_64/kernel/cpuautoplug.c: In function 'do_autoplug_timer':
arch/sw_64/kernel/cpuautoplug.c:455:9: error: implicit declaration of function 'CALC_LOAD' [-Werror=implicit-function-declaration]
  455 |         CALC_LOAD(avenrun[0], EXP_1, active);
      |         ^~~~~~~~~

Signed-off-by: Jing Li <jingli@wxiat.com>
Reviewed-by: He Sheng <hesheng@wxiat.com>
Signed-off-by: Gu Zitao <guzitao@wxiat.com>
(cherry picked from commit f4acf4d8fcfbe709b5828739ac788a44584b61ab)
(cherry picked from commit d36c94d22d55269204c2e9c8b6db17387b6a6e1e)